# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webapp-serv-api-hml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://regconteinerportalaluno.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7535a6c7ac944379b338e718c6f31097 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6bdae09702df49bc9987727f567b6ce7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: regconteinerportalaluno.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7535a6c7ac944379b338e718c6f31097 }}/nestjsmongodb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp-serv-api-hml'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d56b70fb8bd74b75b7b447e26633d0b0 }}
        images: 'regconteinerportalaluno.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7535a6c7ac944379b338e718c6f31097 }}/nestjsmongodb:${{ github.sha }}'