# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webapp-serv-api-hml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://regconteinerportalaluno.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_812e30d7494e45b9b0785b4a2ab0df8e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_08c64a9073d74852bf84fc49f347f120 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: regconteinerportalaluno.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_812e30d7494e45b9b0785b4a2ab0df8e }}/nestjsmongodb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp-serv-api-hml'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bb0ce66076f04ce9b0b3d94e27c91200 }}
        images: 'regconteinerportalaluno.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_812e30d7494e45b9b0785b4a2ab0df8e }}/nestjsmongodb:${{ github.sha }}'